language: generic
sudo: reqwuired

services:
  - docker

before_install:
  - docker build -t Polemarchus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
