language: generic
sudo: reqwuired

services:
  - docker

before_install:
  - docker build -t polemarchus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true polemarchus/docker-react npm run test
